int printf(const char * restrict s, ...);

/* 
SEMÁNTICA DE LA PRIMERA LÍNEA (QUÉ SIGNIFICADO TRANSMITE)
QUÉ ESPERA LA FUNCIÓN:
-EL PRIMER ARGUMENTO ES UN PUNTERO A UN CHAR
-EL CONST SIGNIFICA QUE PUEDE APUNTAR A LA VARIABLE S, PERO 
QUE NO LA VA A MODIFICAR. ES DECIR, S ES UN PUNTERO DE SOLO LECTURA
-S ES EL NOMBRE DE LA VARIABLE
-S PUEDE CAMBIAR DE AL OBJETO AL CUAL APUNTA, PERO COMO ES UN CONST,
NO PUEDE MODIFICAR LO QUE HAY DENTRO.
-RESTRICT INDICA QUE S ESTA APUNTANDO A UN OBJETO,
LO QUE PERMITE QUE EL COMPILADOR SE PUEDA OPTIMIZAR


LAS DIFERENCIAS CONTRA EL HELLO2.C ES QUE NO TRAJO 
TODAS LAS LIBRERIAS DEL INCLUDE, DECLARA PRINTF Y 
ELIMINÓ EL COMENTARIO QUE ESTABA EN LA FUNCIÓN MAIN
*/

int main(void){
int i=42;
 prontf("La respuesta es %d\n");
