#include <stdio.h>
/*
ERRORES:
- ESTÁ MAL ESCRITO PRINTF
- FALTA LA LLAVE QUE CIERRA EL MAIN
- SE DECLARA LA VARIABLE I PERO NO SE USA
- A PRONTF SE LE ESTÁ INDICANDO QUE LE VA A PASAR UN ENTERO PARA IMPRIMIR,
PERO NO SE LE ESTÁ PASANDO LA REFERENCIA
*/
int/*medio*/main(void){
int i=42;
 prontf("La respuesta es %d\n");